### ISSUE TITLE
Age weighted discounting

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#10]
Review YLD and YLL formula's for discounting - do we need to take age weighing into account? I suggest NO. Ask Jim tuesday. Also, we would need incidence and duration to calculate YLD properly. The prevalence way is just a measure for calculating healthy life expectancy in global disease studies, it cannot be used if you discount and/or use age-weighing.

**Comment by alexgoodell** [comment]
Currently we discount costs but not YLDs or YLLs. @Vreman can do

**Comment by Vreman** [comment]
I added the discounting to index.go, just needed to adapt the simple discountValue formula.

Closing this.
