### ISSUE TITLE
Life expectancy tables

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#11]
Discuss life expectancy table - use HALE or LE and should we (and how) extrapolate above age 80? - Discuss with Jim.
    I have extrapolated according to an article in lancet that suggested LE up until 105. Have already put that in.

**Comment by Vreman** [comment]
I have discussed with Jim and extrapolating like that is fine. Have supplied new (discounted) values for health adjusted life expectancy in the excel input files (07-08).

Closing this.
