### ISSUE TITLE
Sugar indirect effects

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#14]
Introduce effects of Sugar->BMI->NAFLD->Diabetes->CHD? - Discuss with Jim

**Comment by Vreman** [comment]
Will discuss this Tuesday 07-07, might need to add some TPs and interactions.

**Comment by Vreman** [comment]
These interactions need to be added to the interaction file.
I have done that. The cosequence of these new interactions is, of course, that I will need to recalibrate and probably change the baseline transition probabilities within most of the models.
I will work on that.

Another interaction that I might be adding is an independent interaction directly from sugar to diabetes. I need to review the literature first.

**Comment by Vreman** [comment]
Reviewd literature and discussed briefly with Jim -> we will not be adding a direct interaction between sugar and T2D or sugar and CHD.
