### ISSUE TITLE
Excel comparison

### ISSUE THREAD

**Issue by Vreman** [alexgoodell/go-mdism#22]
What I have found at 07-07, this includes the new extrapolated HALE estimates, the liver mortality from NASH and cirrhosis, the HCC starting prevalence, undiscounted YLDs and YLLs, the shuffling of the models, and the specific natural mortality regression rates.

edit: updated this post after adding shuffling and correct natural mortality regression rates.

Results that are different between excel and GO (all seen from GO point of view):
- NAFLD steatosis little low (-2%, could be random variation)
- NAFLD NASH little high (+5%, not sure if could be random variation)
- NAFLD Liver death a little high (+10%)
- NAFLD other death little low (-8%)
- CHD is very low (-30%)
- CHD death is very low (-25%) -> prob. because incidence is too low.
- CHD otherdeath is a bit high -> prob. also because incidence is too low.
- T2D has only minor variations (< +/- 3%) is probably because of rand.
- BMI normal weight is way too low (-35%)
- BMI overweight is way too low (-17%)
- BMI obese is way too high (+30%)
- Total otherdeath is correct (will be interesting to see what happens when CHD incidence is raised)
- Age at uninitialized has 1 extra person? = discussed elsewhere
- Age of each new entry is 21 = discussed elsewhere
- Percentage for each age group matched excel and CDC population projections quite well.

**Comment by Vreman** [comment]
My first point of action is the regression rates of the incidence and mortality of CHD and of the natural mortality rate.
I expect it makes a difference that we generalise them for the GO model, while they should really be age specific. I think this is a feature that should not be too hard to build right? I can make an if statement saying the regression rate is dependent on current state in the age model.

I will try and see what happens.

**Comment by alexgoodell** [comment]
Might also be due to non-random execution of models. I've opened a new issue for that https://github.com/alexgoodell/go-mdism/issues/23 and will work on it

**Comment by Vreman** [comment]
Ah that is also a good point. 

As for my own endeavours, I do not know how to access the age of a person within the adjust_transitions function.

I've adapted the code into:		

ageModel := localInputs.Models[7]
ageModelStateId := person.get_state_by_model(localInputs, ageModel).Id
actualAge := ageModelStateId - 22
		
timeEffectByToState := make([]float64, 15, 15)
timeEffectByToState[13] = 0.985 //CHD incidence
timeEffectByToState[14] = 0.979 //CHD mortality
          if actualAge >= 20 && actualAge <= 30 {
                timeEffectByToState[8] = 1.000 //natural deaths
	} else if actualAge > 30 && actualAge <= 55 {
		timeEffectByToState[8] = 0.980 //natural deaths
	} else if actualAge > 55 {
			timeEffectByToState[8] = 0.970 //natural deaths
		} else {
	fmt.Println("Cannot determine regression rate of natural mortality ", timeEffectByToState[8])
	os.Exit(1)
	}

adjustmentFactor = adjustmentFactor * math.Pow(timeEffectByToState[interaction.To_state_id], float64(cycle.Id-2))



The problem here is that 'person' in the line with ageModelStateId is not something I can access in this function. 
Via localInputs.QueryData does not work either. Is there another way to access age in this function?

**Comment by alexgoodell** [comment]
You are right. You will need to pass ```person``` through the ```adjust_transitions()`` function. Just add it as the last variable it accepts.

I'm not sure if I'm following why we need this code in the ```adjust_transitions``` function though
