### ISSUE TITLE
TODO: Re-implement intervention not using adjust_transitions because adjust_transitions now requires a person

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#24]
On file: [index.go](https://github.com/alexgoodell/go-mdism/blob/newSugar/index.go)

**Comment by Vreman** [comment]
I think I fixed that, see lines 218 - 227 in: https://github.com/alexgoodell/go-mdism/blob/newSugar/index.go

**Comment by alexgoodell** [comment]
Great
