### ISSUE TITLE
How to vary the prevalences of the diseases in the ras file during the PSA

### ISSUE THREAD

**Issue by Vreman** [alexgoodell/go-mdism#36]
Because after we vary the baseline probabilities to get a starting prevalence, stille we need them to amount to 1.
Can we put these through a function like adjust_transitions? We would need to add a from_state_id to the RAS file though.

**Comment by alexgoodell** [comment]
right -- we can take the same approach as we planned on doing with the TPs - remove excess from recursive TP where possible, adjust all if needed. We will need a function for PSA adjustment for the TPs and RAS - hopefully we can reuse code for the two

**Comment by Vreman** [comment]
Ok cool, I will add the column to the ras file.

**Comment by Vreman** [comment]
Done that, function for PSA is functioning but needs some improvement. Closing this issue
