### ISSUE TITLE
It is not a problem that different input parameters have the same PSA id?

### ISSUE THREAD

**Issue by Vreman** [alexgoodell/go-mdism#37]
For example, when somebody has high sugar consumption, the OR is relevant for about 7 different transitions (non-NAFLD -> steatosis, non-NAFLD -> NASH, et cetera). 
In the interventions file, we have coded them all seperately, but in the PSA, I want all these interventions all to change to the same variable, so I would put in the same number as PSA_id.

That would not pose any problems right?

**Comment by alexgoodell** [comment]
I don't think it will cause any problems, as long as each variable we want to vary has only one PSA id

**Comment by Vreman** [comment]
Ok, closing this.
