### ISSUE TITLE
Costs and Daly's found at OtherDeath

### ISSUE THREAD

**Issue by Vreman** [alexgoodell/go-mdism#48]
I've coded a macro to analyse the 'output_by_cycle_and_state_full' and the 'output_by_cycle' files.

When I organize all the costs, DALY's, YLD's and YLL's, I find that for each of these elements, there are also values listed in the OtherDeath state within each disease model.

For instance, go to element 549 and 555 in the 'output_by_cycle_and_state_full' file. You will see these otherdeath states have values for YLDs, YLLs, DALYs and Costs.

Another thing, and I suppose they might be related, is that the populations in the OtherDeath states do not add up anymore.
Before, in the state_populations file, the natural+disease specific deaths in 3 of the 4 models, added up to the total of the OtherDeath in the 4th model.
You told me that you had to recode the function for forcing people to the OtherDeath state, so I am not sure if this is supposed to be like this now?

For example: cycle number 3:
Liver death = 10
Natural death = 204
OtherDeath(in NAFLD model) = 54

CHD death = 45
T2D Death = 70

We see that the deaths in the other models (than NAFLD), do not amount to the OtherDeath value that we find in the NAFLD model (115 vs 54).

**Comment by alexgoodell** [comment]
For "When I organize all the costs, DALY's, YLD's and YLL's, I find that for each of these elements, there are also values listed in the OtherDeath state within each disease model."

 Ok i think i understand what is happening - when someone dies in a model, I kill them in all models in the cycle ahead of them. However, if that model already was calculated, it could still have YLD/YLLs from the state that person was supposed to go to. Unfortunately, they died. So those YLD/YLLs should be zero. I will implement that now.

**Comment by alexgoodell** [comment]
Yep. that was it. 

Now on to "Another thing, and I suppose they might be related, is that the populations in the OtherDeath states do not add up anymore.
Before, in the state_populations file, the natural+disease specific deaths in 3 of the 4 models, added up to the total of the OtherDeath in the 4th model."

**Comment by alexgoodell** [comment]
got it. was

``` go
    if Query.Master_record_id_by_cycle_and_person_and_model[cycle.Id+1][person.Id][model.Id] == otherDeathState.Id {
        return
    }
```

now it is

``` go
    if Query.State_id_by_cycle_and_person_and_model[cycle.Id+1][person.Id][model.Id] == otherDeathState.Id {
        return
    }
```

duh! stupid typo. sorry for not testing that...
