### ISSUE TITLE
Cycles

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#5]
Why does it say at inputs 0 (pre) until 25, but at outputs we have year 0 until 26. Those include -1 and -2? But then it seems that cycle 25 does not get simulated? For cycle inputs I have set 0 (2010) until 25 (2035), but it seems that he doesn't simulate 25?

**Comment by alexgoodell** [comment]
We use the cycles to calculate the next cycle. Cycle 0 is all uninitialized, then we use cycle 0 to calculate 0+1, etc. This leaves us with 0 to 25+1.

**Comment by Vreman** [comment]
Agreed, see https://github.com/alexgoodell/go-mdism/issues/12

**Comment by alexgoodell** [comment]
Great, closing this one.
