### ISSUE TITLE
Changes I made over the weekend

### ISSUE THREAD

**Issue by Vreman** [alexgoodell/go-mdism#52]
- Regression rates of CHD incidence and mortality fixed only updated once per cycle.
- Added RAS specific prevalence of NAFLD (only ethnicity-specific).
- Added RAS specific fructose consumption -> had to add state unin2 at Fructose model.
- Only start adding costs & DALY's after 2014 (starting cycle 6 = 2015).
- Discounting only starting at cycle 7
- Added PSA_id's to ras file
- Recalibrated the input parameters so output would match other predictions

**Comment by alexgoodell** [comment]
Closing.
