### ISSUE TITLE
All relevant exports

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#6]
make output file that writes exactly all things we are interested in. If necessary can be combined with excel macro.
 events need to be coded first
make output file for costs, calys, yld and yll and add these to the macro for prevalence - I have made a DALYstoExport file with some functions, I am not sure if it will work because I do not completely understand it (it is similar to the state_populations).
I already have a macro to accurately access all state populations, turn them into graphs and compare those to excel.

**Comment by Vreman** [comment]
See question for PSA reporting
https://github.com/alexgoodell/go-mdism/issues/8

**Comment by alexgoodell** [comment]
Great. I'm closing this one.
