### ISSUE TITLE
 Adjust YLD values

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#7]
- Adjust YLD values - when somebody has 2 diseases simultaneously Dw = 1-PRODUCT(1-Dwx) Where Dwx is each disease specific Dw.
- The same goes for YLL values, if somebody by chance dies in two models at the same time, you should not count those deaths twice. Attribute half to both diseases. -> This is probably not an issue in GO, since you cannot die in two models simultaneously.
- Take half the costs for a disease prevalence when somebody gets the disease in a specific year or when somebody dies from a disease in a specific year. At the moment we count full costs upon incidence and zero costs upon death.

**Comment by Vreman** [comment]
This contribution is likely quite small. I think our main focus at this moment (07-07) should be to code the natural events and other outcomes and see if we can generate a nice mean and confidence interval for future events, prevalences, costs and DALYs.

**Comment by alexgoodell** [comment]
Great. In that case, I will work on https://github.com/alexgoodell/go-mdism/issues/8
