### ISSUE TITLE
How to vary parameters in PSA

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#9]
Define borders and distributions for PSA. How to code this in GO? - Randomly change the input variables? + Also: what happens when a baseline transition probability changes? Do we adjust the rest accordingly or should we subtract/add from/to remaining? Discuss with Jim Tuesday 07-07.

**Comment by Vreman** [comment]
A note on this: I have added the gammav2, betav2 and normalv2 files.
I have placed comments to clarify which values are the parameters that will be varied in the PSA, this is different for each distribution.
We need to think about a way to generate all these random values according to the distribution and replace the matching variable in the inputs by this new parameter.

**Comment by alexgoodell** [comment]
Absolutely. I was thinking we would modify the transition_probabilities.csv to have information about how to vary the parameters, ie:

| Tp_base | Tp_low | Tp_high | Distribution | Beta | Alpha |
| --- | --- | --- | --- | --- | --- |
| 0.03 | 0.01 | 0.05 | Triangular |  |  |
| 0.06 |  |  | Beta | 0.1 | 0.2 |
| 0.06 |  |  | Gamma | 0.2 | 0.4 |

We can then do something like this:

```
if distribution == "beta" {
   transitionPropability.Tp_base = getRandomNumberFromBetaDistribution(alpha, beta)
}
```

**Comment by Vreman** [comment]
Sounds good.
It's not just the TPs though, we also have to vary the OR's in the interaction CSV, the baseline prevalences in the RAS CSV, the costs and the DALY values. But I guess those work with a similar method.
And then when you changed everything you put the TPs through the adjust_transitions function before starting simulation?

And will this work if you run simultaneous iterations?

**Comment by alexgoodell** [comment]
Good point - I forgot about all the other parameters we'll need to vary.

One solution would be to create another table just with information on PSA parameters. Every parameter that will need to be varied can have a psa_id, and we can look up how to vary it.

Maybe we should make the costs, DALYs into tables like we have with the other inputs, instead of hard-coding them into the program.

All the variation will happen before we start running the model at all. It is as if we manually varied things in the input CSVs, so adjust_transitions won't be used for the PSA.

We will need to figure out how to vary transition probabilities in a way that allows the baseline to equal 1. I don't think there are any other big problems that come from varying any of the other parameters.

```
               +-----------------+                 
               | Inputs from CSV |                 
               +--------+--------+                 
                        |                          
       Simulation 1     |    Simulation 2          
         +--------------+----------------+         
         |                               |         
         |                               |         
         |                               |         
         |                               |         
+--------v--------+             +--------v--------+
|Adjust all inputs|             |Adjust all inputs|
+--------+--------+             +--------+--------+
         |                               |         
         |                               |         
         |                               |         
+--------v--------+             +--------v--------+
|     Run model   |             |     Run model   |
+-----------------+             +-----------------+

                        
```

**Comment by Vreman** [comment]
Ok, looks good.

Maybe we can have another column in this PSA file that has a boolean for 'Factor'?
I want to vary most of the incidences and mortality rates between the range that is determined by taking a factor of the baseline TP (0.5 - 2.0), so that would be a nice way to generalize them.

Most of them are beta distributions, which means we need the range as inputs for the beta function, we can determine that range by setting min and max variables as a multiplication of the baseline.

**Comment by alexgoodell** [comment]
We need a psa table that has this setup:

| id | low | high | Distribution | Beta | Alpha | Mean | Std dev | target_table |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 0.03 | 0.01 | 0.05 | Triangular |  |  |  |  | Tp_base |
| 0.06 |  |  | Beta | 0.1 | 0.2 |  |  | DW |
|  |  |  | Gamma | 0.2 | 0.4 |  |  | costs |

And we need a DW table and a Costs table

**Comment by alexgoodell** [comment]
Add a function that allows for non-coherenet (ie, ! = 1) probabilities by mutliplication by inverse of remainder
